// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sikbkeyzzqhkznvrsszl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpa2JrZXl6enFoa3pudnJzc3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjI2MTcsImV4cCI6MjA1NjEzODYxN30.WZxJoq10b40oJJum_N8VoTywRiwog-3nhTBZmf2XMlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);